---
imap_accounts:
  description: "IMAP accounts"
  type: "array"
  required: true
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the account"
        type: "string"
        secret: false
        required: true
      server:
        description: "Email server name - e.g. imap.gmail.com"
        type: "string"
        secret: false
        required: true
      username:
        description: "Mailbox username"
        type: "string"
        required: true
      password:
        description: "Mailbox password."
        type: "string"
        secret: true
        required: true
      port:
        description: "Port to connect to - e.g. 993, 143."
        type: "integer"
        default: 993
        required: true
      secure:
        description: "Set to False to disable secure protocol. Default value is True."
        type: "boolean"
        default: true
      folder:
        description: "Folder to check for email. Default INBOX"
        type: "string"
        required: false
        default: "INBOX"
smtp_accounts:
  description: "SMTP accounts"
  type: "array"
  required: true
  items:
    type: "object"
    required: true
    properties:
      name:
        description: "Name of the account"
        type: "string"
        secret: false
        required: true
      server:
        description: "Email server name - e.g. imap.gmail.com"
        type: "string"
        secret: false
        required: true
      username:
        description: "Mailbox username"
        type: "string"
        required: true
      password:
        description: "Mailbox password."
        type: "string"
        secret: true
        required: true
      port:
        description: "Port to connect to - e.g. 465, 587."
        type: "integer"
        default: 465
        required: true
      secure:
        description: "Set to False to disable secure protocol. Default value is True."
        type: "boolean"
        default: true
      smtp_auth:
        description: "Authenticate username and password with SMTP server to send email. Default True"
        type: "boolean"
        default: true
